markdown: kramdown
permalink: :title
timezone: America/Chicago
permalink: pretty

title: The Website of Josh Kennedy
description: Husband, father, designer, developer, all-around cheeky fellow
url: https://www.joshkennedy.me
author: Josh Kennedy
twitter:
  username: joshkennedy
  card: summary

plugins:
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-purgecss
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-webp

css_dir: "assets/css"

sass:
  style: compressed
  load_paths:
    - _sass
    - node_modules

webp:
  enabled: true
  quality: 85
  img_dir: ["/assets/images"]
  formats: [".jpeg", ".jpg", ".png", ".gif"]
  gifs: [".gif"]
  regenerate: false
  webp_path: nil
  exclude: []

include:
  - .htaccess

exclude:
  - LICENSE
  - README
  - Rakefile
  - bower_components
  - gulpfile.babel.js
  - modernizr-config.json
  - node_modules
  - package.json
